### PR TITLE
Update getting started links

### PR DESCRIPTION
**Pull request by zwalchuk**

### CODE REVIEW

**Comment by floion** [comment]
Hi @zwalchuk the links are not existing at this stage. I will merge this PR when the links are up.
Also, can you also add a CHANGELOG entry as part of this PR to note down this change? As like https://github.com/resin-os/resin-dt-cloudconnector/pull/32/commits/d6d70ac02bffb450c70731d3036a30503f6e520e for example?
Thanks

**Comment by zwalchuk** [comment]
@floion The links are live now, and I've updated the CHANGELOG. I'll do the same with the other ones that need updating

**Comment by floion** [comment]
Thanks @zwalchuk 
Just a small note, you need to configure your git client to also add:

> Signed-off-by: Zachary Walchuk <zach@resin.io>

**Comment by floion** [comment]
Also @zwalchuk this PR was missing the CHANGELOG entry

**Pull request merged**
